name: directuscms

services:
  directus:
    image: directus/directus:11.14.1
    env_file:
      - .env
    ports:
      - ${DIRECTUS_PORT}:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      WEBSOCKETS_ENABLED: "${DIRECTUS_WEBSOCKETS_ENABLED}"
      SECRET: "${DIRECTUS_SECRET}"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.sqlite3"
